# Site settings
title: idoogu
email: hello@idoogu.com
description: ""
keywords:
- coding
- Shanghai
- China
- Taiwan

# URL
url: "https://idoogu.sayidhe.com"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
google_tag_manager: 
google_analytics: 

# SEO
twitter: 
facebook: 
logo: /assets/logo.png
image: /assets/card.png
social:
  - 

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Build settings
exclude: ['README.md', 'Makefile']

# Plugins
plugins:
- jekyll-sitemap

# Multiligual
lang:
  # - en
  - zh

# sass:
#   style: compressed
